# Generated by Django 3.0.7 on 2020-09-24 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='testservicename',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='testorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.CustomerProfile')),
                ('sername', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.testservicename')),
            ],
        ),
        migrations.CreateModel(
            name='testjobrequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.EmployeeProfile')),
            ],
        ),
    ]
