# Generated by Django 3.0.7 on 2020-09-24 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_testjobrequest_testorder_testservicename'),
    ]

    operations = [
        migrations.AddField(
            model_name='testorder',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.testjobrequest'),
        ),
    ]
