# Generated by Django 3.0.7 on 2020-10-04 21:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20201004_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='isApproval',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='leave',
            name='StartDate',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
