# Generated by Django 3.0.8 on 2020-08-11 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_customerprofile_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='lastname',
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='address',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
