# Generated by Django 3.0.7 on 2020-09-24 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_testorder_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testorder',
            name='cus',
        ),
        migrations.RemoveField(
            model_name='testorder',
            name='job',
        ),
        migrations.RemoveField(
            model_name='testorder',
            name='sername',
        ),
        migrations.DeleteModel(
            name='testjobrequest',
        ),
        migrations.DeleteModel(
            name='testorder',
        ),
        migrations.DeleteModel(
            name='testservicename',
        ),
    ]
