# Generated by Django 3.0.7 on 2020-09-29 08:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200924_0621'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeIn', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('timeOut', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='timesheet',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.TimeSheet'),
        ),
    ]
