# Generated by Django 3.0.8 on 2020-08-13 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200811_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeIn', models.DateTimeField()),
                ('timeOut', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='lastname',
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='timesheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.TimeSheet'),
        ),
    ]
