# Generated by Django 3.0.7 on 2020-10-05 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20201004_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='isReject',
            field=models.BooleanField(default=False),
        ),
    ]
