# Generated by Django 3.0.8 on 2020-08-13 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200813_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='timeIn',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='timeOut',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
