# Generated by Django 3.0.7 on 2020-10-05 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_leave_isreject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.GroupEmployee'),
        ),
    ]
