# Generated by Django 3.0.8 on 2020-08-13 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200813_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='timeIn',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='timeOut',
            field=models.DateTimeField(),
        ),
    ]
