# Generated by Django 3.0.7 on 2020-09-30 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200930_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='Day',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
