# Generated by Django 3.0.7 on 2020-10-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20201005_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='address',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='phone',
            field=models.TextField(blank=True, max_length=11, null=True),
        ),
    ]
