# Generated by Django 3.0.7 on 2020-09-30 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_timesheet_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='timesheet',
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='timesheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.TimeSheet'),
        ),
    ]
