# Generated by Django 3.0.7 on 2020-09-30 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20200930_0133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='timesheet',
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='timesheet',
            field=models.ManyToManyField(to='account.TimeSheet'),
        ),
    ]
