# Generated by Django 3.0.7 on 2020-10-01 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20200930_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='isLast',
            field=models.BooleanField(default=False),
        ),
    ]
