# Generated by Django 3.0.7 on 2020-10-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_timesheet_islast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='timeIn',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='timeOut',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
