# Generated by Django 3.0.7 on 2020-10-02 00:38

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_google_maps.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=50, null=True)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_order', models.DateTimeField(default=datetime.datetime.now)),
                ('fullName', models.TextField(blank=True, max_length=50, null=True)),
                ('phoneNumber', models.TextField(blank=True, max_length=20, null=True)),
                ('server_date', models.DateTimeField(blank=True, null=True)),
                ('complete', models.BooleanField(default=False)),
                ('assigned', models.BooleanField(default=False)),
                ('isService', models.BooleanField(default=False)),
                ('isPropety', models.BooleanField(default=False)),
                ('isDone', models.BooleanField(default=False)),
                ('isPaid', models.BooleanField(default=False)),
                ('address', django_google_maps.fields.AddressField(max_length=200, null=True)),
                ('geolocation', django_google_maps.fields.GeoLocationField(max_length=100, null=True)),
                ('feedbackETC', models.CharField(blank=True, max_length=255, null=True)),
                ('feedbackCTE', models.CharField(blank=True, max_length=255, null=True)),
                ('cus_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.CustomerProfile')),
                ('employee_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.EmployeeProfile')),
            ],
        ),
        migrations.CreateModel(
            name='PropetyServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=50, null=True)),
                ('price', models.IntegerField(null=True)),
                ('description', models.TextField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=50, null=True)),
                ('price', models.IntegerField(null=True)),
                ('description', models.TextField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_required', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('notes', models.TextField(blank=True, max_length=100)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Oneshop.Order')),
                ('security_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Oneshop.SecurityServices')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_required', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('notes', models.TextField(blank=True, max_length=100)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Oneshop.Order')),
                ('property_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Oneshop.PropetyServices')),
            ],
        ),
        migrations.CreateModel(
            name='HiringOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_order', models.DateTimeField(default=datetime.datetime.now)),
                ('complete', models.BooleanField(default=False)),
                ('assigned', models.BooleanField(default=False)),
                ('isPaid', models.BooleanField(default=False)),
                ('isPickup', models.BooleanField(default=False)),
                ('isDelivery', models.BooleanField(default=False)),
                ('isDone', models.BooleanField(default=False)),
                ('address', django_google_maps.fields.AddressField(blank=True, max_length=200, null=True)),
                ('geolocation', django_google_maps.fields.GeoLocationField(blank=True, max_length=100, null=True)),
                ('fullName', models.TextField(blank=True, max_length=50, null=True)),
                ('phoneNumber', models.TextField(blank=True, max_length=20, null=True)),
                ('leash_date', models.DateTimeField(blank=True, null=True)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('feedbackETC', models.CharField(blank=True, max_length=255, null=True)),
                ('feedbackCTE', models.CharField(blank=True, max_length=255, null=True)),
                ('cus_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.CustomerProfile')),
                ('employee_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.EmployeeProfile')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Oneshop.Equipment')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Oneshop.HiringOrder')),
            ],
        ),
    ]
