# Generated by Django 3.0.8 on 2020-08-06 06:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equiement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=50, null=True)),
                ('stock', models.IntegerField(blank=True, max_length=999, null=True)),
                ('price', models.IntegerField(blank=True, max_length=9999, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('price', models.IntegerField(max_length=10, null=True)),
                ('cus_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.CustomerProfile')),
                ('employee_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.EmployeeProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('feedback_order_cusToem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.CustomerProfile')),
                ('feedback_order_emTocus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.EmployeeProfile')),
            ],
        ),
    ]
