# Generated by Django 3.0.7 on 2020-09-20 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oneshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiringorder',
            name='isPaid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='isPaid',
            field=models.BooleanField(default=False),
        ),
    ]
