# Generated by Django 3.0.8 on 2020-08-07 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200807_2051'),
        ('Oneshop', '0002_auto_20200807_2051'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeedbackcusToem',
            new_name='CustomerFeedback',
        ),
        migrations.RenameModel(
            old_name='FeedbackemTocus',
            new_name='EmployeeFeedback',
        ),
    ]
