# Generated by Django 3.0.7 on 2020-09-25 22:46

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Oneshop', '0002_hiringorder_isdone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiringorder',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(blank=True, default='-36.848461, 174.763336', max_length=100, null=True),
        ),
    ]
