# Generated by Django 3.0.7 on 2020-09-20 23:26

import datetime
from django.db import migrations, models
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Oneshop', '0002_auto_20200920_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiringorder',
            name='address',
            field=django_google_maps.fields.AddressField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hiringorder',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hiringorder',
            name='isDelivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hiringorder',
            name='isPickup',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hiringorder',
            name='date_order',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_order',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
