# Generated by Django 3.0.8 on 2020-08-25 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oneshop', '0002_auto_20200825_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Accept'), ('D', 'Finish')], default='Pending', max_length=1),
        ),
    ]
