# Generated by Django 3.0.7 on 2020-09-25 23:37

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Oneshop', '0003_auto_20200925_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiringorder',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(blank=True, max_length=100, null=True),
        ),
    ]
