# Generated by Django 3.0.8 on 2020-08-10 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oneshop', '0004_auto_20200809_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicesorder',
            name='order',
        ),
        migrations.RemoveField(
            model_name='servicesorder',
            name='service',
        ),
        migrations.RemoveField(
            model_name='order',
            name='service_order',
        ),
        migrations.AddField(
            model_name='order',
            name='equiement',
            field=models.ManyToManyField(to='Oneshop.Equiement'),
        ),
        migrations.AddField(
            model_name='order',
            name='service',
            field=models.ManyToManyField(to='Oneshop.Services'),
        ),
        migrations.DeleteModel(
            name='EquiementOrder',
        ),
        migrations.DeleteModel(
            name='ServicesOrder',
        ),
    ]
