# Generated by Django 3.0.7 on 2020-09-28 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oneshop', '0004_auto_20200925_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='propetyservices',
            name='test',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
