# Generated by Django 3.0.8 on 2020-08-25 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Oneshop', '0005_order_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_status',
            new_name='assigned',
        ),
    ]
