# Generated by Django 3.0.8 on 2020-08-29 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oneshop', '0006_auto_20200825_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
