# Generated by Django 3.0.8 on 2020-08-11 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oneshop', '0006_auto_20200810_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equiementorder',
            name='equipment',
        ),
        migrations.AddField(
            model_name='equiementorder',
            name='equipment',
            field=models.ManyToManyField(to='Oneshop.Equipment'),
        ),
    ]
