# Generated by Django 3.0.7 on 2020-09-29 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Oneshop', '0006_auto_20200928_0733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propetyservices',
            name='test',
        ),
    ]
