# Generated by Django 3.0.8 on 2020-08-12 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200811_1450'),
        ('Oneshop', '0007_auto_20200811_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cus_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.CustomerProfile'),
        ),
        migrations.AlterField(
            model_name='order',
            name='employee_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.EmployeeProfile'),
        ),
    ]
