# Generated by Django 3.0.8 on 2020-08-29 09:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oneshop', '0008_auto_20200829_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyorder',
            name='date_required',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='securityorder',
            name='date_required',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
