# Generated by Django 3.0.8 on 2020-08-29 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oneshop', '0009_auto_20200829_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyorder',
            name='description',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='securityorder',
            name='description',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
