# Generated by Django 3.0.8 on 2020-08-15 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Oneshop', '0009_auto_20200815_1324'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EquiementOrder',
        ),
    ]
