# Generated by Django 3.0.8 on 2020-09-02 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oneshop', '0010_auto_20200829_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='isHiring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='isPropety',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='isService',
            field=models.BooleanField(default=False),
        ),
    ]
