# Generated by Django 3.0.8 on 2020-09-05 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oneshop', '0011_auto_20200902_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='leash_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
