# Generated by Django 3.0.8 on 2020-08-18 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Oneshop', '0012_auto_20200816_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=50, null=True)),
                ('price', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='servicesorder',
            name='service',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.RenameModel(
            old_name='Services',
            new_name='PropetyServices',
        ),
        migrations.CreateModel(
            name='PropertyOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_added', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Oneshop.Order')),
                ('property_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Oneshop.PropetyServices')),
            ],
        ),
        migrations.AddField(
            model_name='servicesorder',
            name='security_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Oneshop.SecurityServices'),
        ),
    ]
