# Generated by Django 3.0.8 on 2020-08-19 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Oneshop', '0013_auto_20200819_1145'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServicesOrder',
            new_name='SecurityOrder',
        ),
    ]
