# Generated by Django 3.0.8 on 2020-09-05 00:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('Oneshop', '0013_auto_20200905_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='isHiring',
        ),
        migrations.CreateModel(
            name='HiringOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_order', models.DateTimeField(default=django.utils.timezone.now)),
                ('complete', models.BooleanField(default=False)),
                ('assigned', models.BooleanField(default=False)),
                ('leash_date', models.DateTimeField(blank=True, null=True)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('feedbackETC', models.CharField(blank=True, max_length=255, null=True)),
                ('feedbackCTE', models.CharField(blank=True, max_length=255, null=True)),
                ('cus_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.CustomerProfile')),
                ('employee_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.EmployeeProfile')),
            ],
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Oneshop.HiringOrder'),
        ),
    ]
