# Generated by Django 3.0.8 on 2020-09-10 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oneshop', '0014_auto_20200905_1244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyorder',
            old_name='description',
            new_name='notes',
        ),
        migrations.RenameField(
            model_name='securityorder',
            old_name='description',
            new_name='notes',
        ),
        migrations.AddField(
            model_name='propetyservices',
            name='description',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='securityservices',
            name='description',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
