# Generated by Django 3.0.8 on 2020-09-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oneshop', '0015_auto_20200910_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='isDone',
            field=models.BooleanField(default=False),
        ),
    ]
