# Generated by Django 3.0.8 on 2020-09-13 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oneshop', '0016_order_isdone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
