# Generated by Django 3.0.8 on 2020-09-13 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oneshop', '0017_order_order_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='server_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
