# Generated by Django 3.0.7 on 2020-09-15 03:36

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Oneshop', '0018_order_server_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=django_google_maps.fields.AddressField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(max_length=100, null=True),
        ),
    ]
