# Generated by Django 3.0.7 on 2020-09-15 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Oneshop', '0019_auto_20200915_0336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_location',
        ),
    ]
